/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * LeadFlow CRM API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";
/**
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
}, {
    status: string;
}>;
/**
 * @summary Register a new user
 */
export declare const RegisterBody: zod.ZodObject<{
    name: zod.ZodString;
    email: zod.ZodString;
    password: zod.ZodString;
    role: zod.ZodOptional<zod.ZodEnum<["admin", "member", "client"]>>;
}, "strip", zod.ZodTypeAny, {
    name: string;
    email: string;
    password: string;
    role?: "admin" | "member" | "client" | undefined;
}, {
    name: string;
    email: string;
    password: string;
    role?: "admin" | "member" | "client" | undefined;
}>;
/**
 * @summary Log in
 */
export declare const LoginBody: zod.ZodObject<{
    email: zod.ZodString;
    password: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    email: string;
    password: string;
}, {
    email: string;
    password: string;
}>;
export declare const LoginResponse: zod.ZodObject<{
    token: zod.ZodString;
    user: zod.ZodObject<{
        id: zod.ZodNumber;
        name: zod.ZodString;
        email: zod.ZodString;
        role: zod.ZodEnum<["admin", "member", "client"]>;
        active: zod.ZodBoolean;
        createdAt: zod.ZodDate;
        updatedAt: zod.ZodDate;
    }, "strip", zod.ZodTypeAny, {
        name: string;
        email: string;
        role: "admin" | "member" | "client";
        id: number;
        active: boolean;
        createdAt: Date;
        updatedAt: Date;
    }, {
        name: string;
        email: string;
        role: "admin" | "member" | "client";
        id: number;
        active: boolean;
        createdAt: Date;
        updatedAt: Date;
    }>;
}, "strip", zod.ZodTypeAny, {
    token: string;
    user: {
        name: string;
        email: string;
        role: "admin" | "member" | "client";
        id: number;
        active: boolean;
        createdAt: Date;
        updatedAt: Date;
    };
}, {
    token: string;
    user: {
        name: string;
        email: string;
        role: "admin" | "member" | "client";
        id: number;
        active: boolean;
        createdAt: Date;
        updatedAt: Date;
    };
}>;
/**
 * @summary Get current user
 */
export declare const GetMeResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    email: zod.ZodString;
    role: zod.ZodEnum<["admin", "member", "client"]>;
    active: zod.ZodBoolean;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    name: string;
    email: string;
    role: "admin" | "member" | "client";
    id: number;
    active: boolean;
    createdAt: Date;
    updatedAt: Date;
}, {
    name: string;
    email: string;
    role: "admin" | "member" | "client";
    id: number;
    active: boolean;
    createdAt: Date;
    updatedAt: Date;
}>;
/**
 * @summary List all users (admin)
 */
export declare const ListUsersResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    email: zod.ZodString;
    role: zod.ZodEnum<["admin", "member", "client"]>;
    active: zod.ZodBoolean;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    name: string;
    email: string;
    role: "admin" | "member" | "client";
    id: number;
    active: boolean;
    createdAt: Date;
    updatedAt: Date;
}, {
    name: string;
    email: string;
    role: "admin" | "member" | "client";
    id: number;
    active: boolean;
    createdAt: Date;
    updatedAt: Date;
}>;
export declare const ListUsersResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    email: zod.ZodString;
    role: zod.ZodEnum<["admin", "member", "client"]>;
    active: zod.ZodBoolean;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    name: string;
    email: string;
    role: "admin" | "member" | "client";
    id: number;
    active: boolean;
    createdAt: Date;
    updatedAt: Date;
}, {
    name: string;
    email: string;
    role: "admin" | "member" | "client";
    id: number;
    active: boolean;
    createdAt: Date;
    updatedAt: Date;
}>, "many">;
/**
 * @summary Create a team member or client user
 */
export declare const CreateUserBody: zod.ZodObject<{
    name: zod.ZodString;
    email: zod.ZodString;
    password: zod.ZodString;
    role: zod.ZodEnum<["admin", "member", "client"]>;
}, "strip", zod.ZodTypeAny, {
    name: string;
    email: string;
    password: string;
    role: "admin" | "member" | "client";
}, {
    name: string;
    email: string;
    password: string;
    role: "admin" | "member" | "client";
}>;
/**
 * @summary Get user by ID
 */
export declare const GetUserParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetUserResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    email: zod.ZodString;
    role: zod.ZodEnum<["admin", "member", "client"]>;
    active: zod.ZodBoolean;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    name: string;
    email: string;
    role: "admin" | "member" | "client";
    id: number;
    active: boolean;
    createdAt: Date;
    updatedAt: Date;
}, {
    name: string;
    email: string;
    role: "admin" | "member" | "client";
    id: number;
    active: boolean;
    createdAt: Date;
    updatedAt: Date;
}>;
/**
 * @summary Update user
 */
export declare const UpdateUserParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateUserBody: zod.ZodObject<{
    name: zod.ZodOptional<zod.ZodString>;
    email: zod.ZodOptional<zod.ZodString>;
    role: zod.ZodOptional<zod.ZodEnum<["admin", "member", "client"]>>;
    active: zod.ZodOptional<zod.ZodBoolean>;
}, "strip", zod.ZodTypeAny, {
    name?: string | undefined;
    email?: string | undefined;
    role?: "admin" | "member" | "client" | undefined;
    active?: boolean | undefined;
}, {
    name?: string | undefined;
    email?: string | undefined;
    role?: "admin" | "member" | "client" | undefined;
    active?: boolean | undefined;
}>;
export declare const UpdateUserResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    email: zod.ZodString;
    role: zod.ZodEnum<["admin", "member", "client"]>;
    active: zod.ZodBoolean;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    name: string;
    email: string;
    role: "admin" | "member" | "client";
    id: number;
    active: boolean;
    createdAt: Date;
    updatedAt: Date;
}, {
    name: string;
    email: string;
    role: "admin" | "member" | "client";
    id: number;
    active: boolean;
    createdAt: Date;
    updatedAt: Date;
}>;
/**
 * @summary Delete user
 */
export declare const DeleteUserParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
/**
 * @summary List leads
 */
export declare const ListLeadsQueryParams: zod.ZodObject<{
    stage: zod.ZodOptional<zod.ZodString>;
    category: zod.ZodOptional<zod.ZodString>;
    search: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    stage?: string | undefined;
    category?: string | undefined;
    search?: string | undefined;
}, {
    stage?: string | undefined;
    category?: string | undefined;
    search?: string | undefined;
}>;
export declare const ListLeadsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    businessName: zod.ZodString;
    ownerName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    phone: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    email: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    address: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    website: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    category: zod.ZodString;
    stage: zod.ZodEnum<["new", "contacted", "interested", "qualified", "proposal_sent", "closed", "delivered", "upsell"]>;
    leadScore: zod.ZodNumber;
    notes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    assignedTo: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    createdAt: Date;
    updatedAt: Date;
    stage: "new" | "contacted" | "interested" | "qualified" | "proposal_sent" | "closed" | "delivered" | "upsell";
    category: string;
    businessName: string;
    leadScore: number;
    email?: string | null | undefined;
    ownerName?: string | null | undefined;
    phone?: string | null | undefined;
    address?: string | null | undefined;
    website?: string | null | undefined;
    notes?: string | null | undefined;
    assignedTo?: number | null | undefined;
}, {
    id: number;
    createdAt: Date;
    updatedAt: Date;
    stage: "new" | "contacted" | "interested" | "qualified" | "proposal_sent" | "closed" | "delivered" | "upsell";
    category: string;
    businessName: string;
    leadScore: number;
    email?: string | null | undefined;
    ownerName?: string | null | undefined;
    phone?: string | null | undefined;
    address?: string | null | undefined;
    website?: string | null | undefined;
    notes?: string | null | undefined;
    assignedTo?: number | null | undefined;
}>;
export declare const ListLeadsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    businessName: zod.ZodString;
    ownerName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    phone: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    email: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    address: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    website: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    category: zod.ZodString;
    stage: zod.ZodEnum<["new", "contacted", "interested", "qualified", "proposal_sent", "closed", "delivered", "upsell"]>;
    leadScore: zod.ZodNumber;
    notes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    assignedTo: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    createdAt: Date;
    updatedAt: Date;
    stage: "new" | "contacted" | "interested" | "qualified" | "proposal_sent" | "closed" | "delivered" | "upsell";
    category: string;
    businessName: string;
    leadScore: number;
    email?: string | null | undefined;
    ownerName?: string | null | undefined;
    phone?: string | null | undefined;
    address?: string | null | undefined;
    website?: string | null | undefined;
    notes?: string | null | undefined;
    assignedTo?: number | null | undefined;
}, {
    id: number;
    createdAt: Date;
    updatedAt: Date;
    stage: "new" | "contacted" | "interested" | "qualified" | "proposal_sent" | "closed" | "delivered" | "upsell";
    category: string;
    businessName: string;
    leadScore: number;
    email?: string | null | undefined;
    ownerName?: string | null | undefined;
    phone?: string | null | undefined;
    address?: string | null | undefined;
    website?: string | null | undefined;
    notes?: string | null | undefined;
    assignedTo?: number | null | undefined;
}>, "many">;
/**
 * @summary Create a lead
 */
export declare const CreateLeadBody: zod.ZodObject<{
    businessName: zod.ZodString;
    ownerName: zod.ZodOptional<zod.ZodString>;
    phone: zod.ZodOptional<zod.ZodString>;
    email: zod.ZodOptional<zod.ZodString>;
    address: zod.ZodOptional<zod.ZodString>;
    website: zod.ZodOptional<zod.ZodString>;
    category: zod.ZodString;
    stage: zod.ZodOptional<zod.ZodEnum<["new", "contacted", "interested", "qualified", "proposal_sent", "closed", "delivered", "upsell"]>>;
    leadScore: zod.ZodOptional<zod.ZodNumber>;
    notes: zod.ZodOptional<zod.ZodString>;
    assignedTo: zod.ZodOptional<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    category: string;
    businessName: string;
    email?: string | undefined;
    stage?: "new" | "contacted" | "interested" | "qualified" | "proposal_sent" | "closed" | "delivered" | "upsell" | undefined;
    ownerName?: string | undefined;
    phone?: string | undefined;
    address?: string | undefined;
    website?: string | undefined;
    leadScore?: number | undefined;
    notes?: string | undefined;
    assignedTo?: number | undefined;
}, {
    category: string;
    businessName: string;
    email?: string | undefined;
    stage?: "new" | "contacted" | "interested" | "qualified" | "proposal_sent" | "closed" | "delivered" | "upsell" | undefined;
    ownerName?: string | undefined;
    phone?: string | undefined;
    address?: string | undefined;
    website?: string | undefined;
    leadScore?: number | undefined;
    notes?: string | undefined;
    assignedTo?: number | undefined;
}>;
/**
 * @summary Get lead by ID
 */
export declare const GetLeadParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetLeadResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    businessName: zod.ZodString;
    ownerName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    phone: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    email: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    address: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    website: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    category: zod.ZodString;
    stage: zod.ZodEnum<["new", "contacted", "interested", "qualified", "proposal_sent", "closed", "delivered", "upsell"]>;
    leadScore: zod.ZodNumber;
    notes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    assignedTo: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    createdAt: Date;
    updatedAt: Date;
    stage: "new" | "contacted" | "interested" | "qualified" | "proposal_sent" | "closed" | "delivered" | "upsell";
    category: string;
    businessName: string;
    leadScore: number;
    email?: string | null | undefined;
    ownerName?: string | null | undefined;
    phone?: string | null | undefined;
    address?: string | null | undefined;
    website?: string | null | undefined;
    notes?: string | null | undefined;
    assignedTo?: number | null | undefined;
}, {
    id: number;
    createdAt: Date;
    updatedAt: Date;
    stage: "new" | "contacted" | "interested" | "qualified" | "proposal_sent" | "closed" | "delivered" | "upsell";
    category: string;
    businessName: string;
    leadScore: number;
    email?: string | null | undefined;
    ownerName?: string | null | undefined;
    phone?: string | null | undefined;
    address?: string | null | undefined;
    website?: string | null | undefined;
    notes?: string | null | undefined;
    assignedTo?: number | null | undefined;
}>;
/**
 * @summary Update lead
 */
export declare const UpdateLeadParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateLeadBody: zod.ZodObject<{
    businessName: zod.ZodOptional<zod.ZodString>;
    ownerName: zod.ZodOptional<zod.ZodString>;
    phone: zod.ZodOptional<zod.ZodString>;
    email: zod.ZodOptional<zod.ZodString>;
    address: zod.ZodOptional<zod.ZodString>;
    website: zod.ZodOptional<zod.ZodString>;
    category: zod.ZodOptional<zod.ZodString>;
    stage: zod.ZodOptional<zod.ZodEnum<["new", "contacted", "interested", "qualified", "proposal_sent", "closed", "delivered", "upsell"]>>;
    leadScore: zod.ZodOptional<zod.ZodNumber>;
    notes: zod.ZodOptional<zod.ZodString>;
    assignedTo: zod.ZodOptional<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    email?: string | undefined;
    stage?: "new" | "contacted" | "interested" | "qualified" | "proposal_sent" | "closed" | "delivered" | "upsell" | undefined;
    category?: string | undefined;
    businessName?: string | undefined;
    ownerName?: string | undefined;
    phone?: string | undefined;
    address?: string | undefined;
    website?: string | undefined;
    leadScore?: number | undefined;
    notes?: string | undefined;
    assignedTo?: number | undefined;
}, {
    email?: string | undefined;
    stage?: "new" | "contacted" | "interested" | "qualified" | "proposal_sent" | "closed" | "delivered" | "upsell" | undefined;
    category?: string | undefined;
    businessName?: string | undefined;
    ownerName?: string | undefined;
    phone?: string | undefined;
    address?: string | undefined;
    website?: string | undefined;
    leadScore?: number | undefined;
    notes?: string | undefined;
    assignedTo?: number | undefined;
}>;
export declare const UpdateLeadResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    businessName: zod.ZodString;
    ownerName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    phone: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    email: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    address: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    website: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    category: zod.ZodString;
    stage: zod.ZodEnum<["new", "contacted", "interested", "qualified", "proposal_sent", "closed", "delivered", "upsell"]>;
    leadScore: zod.ZodNumber;
    notes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    assignedTo: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    createdAt: Date;
    updatedAt: Date;
    stage: "new" | "contacted" | "interested" | "qualified" | "proposal_sent" | "closed" | "delivered" | "upsell";
    category: string;
    businessName: string;
    leadScore: number;
    email?: string | null | undefined;
    ownerName?: string | null | undefined;
    phone?: string | null | undefined;
    address?: string | null | undefined;
    website?: string | null | undefined;
    notes?: string | null | undefined;
    assignedTo?: number | null | undefined;
}, {
    id: number;
    createdAt: Date;
    updatedAt: Date;
    stage: "new" | "contacted" | "interested" | "qualified" | "proposal_sent" | "closed" | "delivered" | "upsell";
    category: string;
    businessName: string;
    leadScore: number;
    email?: string | null | undefined;
    ownerName?: string | null | undefined;
    phone?: string | null | undefined;
    address?: string | null | undefined;
    website?: string | null | undefined;
    notes?: string | null | undefined;
    assignedTo?: number | null | undefined;
}>;
/**
 * @summary Delete lead
 */
export declare const DeleteLeadParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
/**
 * @summary Convert lead to client
 */
export declare const ConvertLeadToClientParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
/**
 * @summary List clients
 */
export declare const ListClientsQueryParams: zod.ZodObject<{
    status: zod.ZodOptional<zod.ZodString>;
    search: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    status?: string | undefined;
    search?: string | undefined;
}, {
    status?: string | undefined;
    search?: string | undefined;
}>;
export declare const ListClientsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    businessName: zod.ZodString;
    ownerName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    phone: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    email: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    address: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    website: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    industry: zod.ZodString;
    status: zod.ZodEnum<["active", "inactive", "churned"]>;
    totalRevenue: zod.ZodNumber;
    notes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    status: "active" | "inactive" | "churned";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    businessName: string;
    industry: string;
    totalRevenue: number;
    email?: string | null | undefined;
    ownerName?: string | null | undefined;
    phone?: string | null | undefined;
    address?: string | null | undefined;
    website?: string | null | undefined;
    notes?: string | null | undefined;
}, {
    status: "active" | "inactive" | "churned";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    businessName: string;
    industry: string;
    totalRevenue: number;
    email?: string | null | undefined;
    ownerName?: string | null | undefined;
    phone?: string | null | undefined;
    address?: string | null | undefined;
    website?: string | null | undefined;
    notes?: string | null | undefined;
}>;
export declare const ListClientsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    businessName: zod.ZodString;
    ownerName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    phone: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    email: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    address: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    website: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    industry: zod.ZodString;
    status: zod.ZodEnum<["active", "inactive", "churned"]>;
    totalRevenue: zod.ZodNumber;
    notes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    status: "active" | "inactive" | "churned";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    businessName: string;
    industry: string;
    totalRevenue: number;
    email?: string | null | undefined;
    ownerName?: string | null | undefined;
    phone?: string | null | undefined;
    address?: string | null | undefined;
    website?: string | null | undefined;
    notes?: string | null | undefined;
}, {
    status: "active" | "inactive" | "churned";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    businessName: string;
    industry: string;
    totalRevenue: number;
    email?: string | null | undefined;
    ownerName?: string | null | undefined;
    phone?: string | null | undefined;
    address?: string | null | undefined;
    website?: string | null | undefined;
    notes?: string | null | undefined;
}>, "many">;
/**
 * @summary Create a client
 */
export declare const CreateClientBody: zod.ZodObject<{
    businessName: zod.ZodString;
    ownerName: zod.ZodOptional<zod.ZodString>;
    phone: zod.ZodOptional<zod.ZodString>;
    email: zod.ZodOptional<zod.ZodString>;
    address: zod.ZodOptional<zod.ZodString>;
    website: zod.ZodOptional<zod.ZodString>;
    industry: zod.ZodString;
    status: zod.ZodOptional<zod.ZodEnum<["active", "inactive", "churned"]>>;
    notes: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    businessName: string;
    industry: string;
    status?: "active" | "inactive" | "churned" | undefined;
    email?: string | undefined;
    ownerName?: string | undefined;
    phone?: string | undefined;
    address?: string | undefined;
    website?: string | undefined;
    notes?: string | undefined;
}, {
    businessName: string;
    industry: string;
    status?: "active" | "inactive" | "churned" | undefined;
    email?: string | undefined;
    ownerName?: string | undefined;
    phone?: string | undefined;
    address?: string | undefined;
    website?: string | undefined;
    notes?: string | undefined;
}>;
/**
 * @summary Get client by ID
 */
export declare const GetClientParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetClientResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    businessName: zod.ZodString;
    ownerName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    phone: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    email: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    address: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    website: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    industry: zod.ZodString;
    status: zod.ZodEnum<["active", "inactive", "churned"]>;
    totalRevenue: zod.ZodNumber;
    notes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    status: "active" | "inactive" | "churned";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    businessName: string;
    industry: string;
    totalRevenue: number;
    email?: string | null | undefined;
    ownerName?: string | null | undefined;
    phone?: string | null | undefined;
    address?: string | null | undefined;
    website?: string | null | undefined;
    notes?: string | null | undefined;
}, {
    status: "active" | "inactive" | "churned";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    businessName: string;
    industry: string;
    totalRevenue: number;
    email?: string | null | undefined;
    ownerName?: string | null | undefined;
    phone?: string | null | undefined;
    address?: string | null | undefined;
    website?: string | null | undefined;
    notes?: string | null | undefined;
}>;
/**
 * @summary Update client
 */
export declare const UpdateClientParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateClientBody: zod.ZodObject<{
    businessName: zod.ZodOptional<zod.ZodString>;
    ownerName: zod.ZodOptional<zod.ZodString>;
    phone: zod.ZodOptional<zod.ZodString>;
    email: zod.ZodOptional<zod.ZodString>;
    address: zod.ZodOptional<zod.ZodString>;
    website: zod.ZodOptional<zod.ZodString>;
    industry: zod.ZodOptional<zod.ZodString>;
    status: zod.ZodOptional<zod.ZodEnum<["active", "inactive", "churned"]>>;
    totalRevenue: zod.ZodOptional<zod.ZodNumber>;
    notes: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    status?: "active" | "inactive" | "churned" | undefined;
    email?: string | undefined;
    businessName?: string | undefined;
    ownerName?: string | undefined;
    phone?: string | undefined;
    address?: string | undefined;
    website?: string | undefined;
    notes?: string | undefined;
    industry?: string | undefined;
    totalRevenue?: number | undefined;
}, {
    status?: "active" | "inactive" | "churned" | undefined;
    email?: string | undefined;
    businessName?: string | undefined;
    ownerName?: string | undefined;
    phone?: string | undefined;
    address?: string | undefined;
    website?: string | undefined;
    notes?: string | undefined;
    industry?: string | undefined;
    totalRevenue?: number | undefined;
}>;
export declare const UpdateClientResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    businessName: zod.ZodString;
    ownerName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    phone: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    email: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    address: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    website: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    industry: zod.ZodString;
    status: zod.ZodEnum<["active", "inactive", "churned"]>;
    totalRevenue: zod.ZodNumber;
    notes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    status: "active" | "inactive" | "churned";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    businessName: string;
    industry: string;
    totalRevenue: number;
    email?: string | null | undefined;
    ownerName?: string | null | undefined;
    phone?: string | null | undefined;
    address?: string | null | undefined;
    website?: string | null | undefined;
    notes?: string | null | undefined;
}, {
    status: "active" | "inactive" | "churned";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    businessName: string;
    industry: string;
    totalRevenue: number;
    email?: string | null | undefined;
    ownerName?: string | null | undefined;
    phone?: string | null | undefined;
    address?: string | null | undefined;
    website?: string | null | undefined;
    notes?: string | null | undefined;
}>;
/**
 * @summary Delete client
 */
export declare const DeleteClientParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
/**
 * @summary List orders
 */
export declare const ListOrdersQueryParams: zod.ZodObject<{
    status: zod.ZodOptional<zod.ZodString>;
    clientId: zod.ZodOptional<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    status?: string | undefined;
    clientId?: number | undefined;
}, {
    status?: string | undefined;
    clientId?: number | undefined;
}>;
export declare const ListOrdersResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    clientId: zod.ZodNumber;
    serviceId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    title: zod.ZodString;
    packageType: zod.ZodEnum<["basic_website", "premium_website", "seo", "hosting", "maintenance", "ads_management", "reputation_management", "custom"]>;
    status: zod.ZodEnum<["pending", "paid", "in_progress", "review", "delivered", "maintenance", "cancelled"]>;
    totalAmount: zod.ZodNumber;
    paidAmount: zod.ZodNumber;
    dueDate: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    deliveredAt: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    notes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    status: "delivered" | "maintenance" | "pending" | "paid" | "in_progress" | "review" | "cancelled";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    clientId: number;
    title: string;
    packageType: "custom" | "basic_website" | "premium_website" | "seo" | "hosting" | "maintenance" | "ads_management" | "reputation_management";
    totalAmount: number;
    paidAmount: number;
    notes?: string | null | undefined;
    serviceId?: number | null | undefined;
    dueDate?: Date | null | undefined;
    deliveredAt?: Date | null | undefined;
}, {
    status: "delivered" | "maintenance" | "pending" | "paid" | "in_progress" | "review" | "cancelled";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    clientId: number;
    title: string;
    packageType: "custom" | "basic_website" | "premium_website" | "seo" | "hosting" | "maintenance" | "ads_management" | "reputation_management";
    totalAmount: number;
    paidAmount: number;
    notes?: string | null | undefined;
    serviceId?: number | null | undefined;
    dueDate?: Date | null | undefined;
    deliveredAt?: Date | null | undefined;
}>;
export declare const ListOrdersResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    clientId: zod.ZodNumber;
    serviceId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    title: zod.ZodString;
    packageType: zod.ZodEnum<["basic_website", "premium_website", "seo", "hosting", "maintenance", "ads_management", "reputation_management", "custom"]>;
    status: zod.ZodEnum<["pending", "paid", "in_progress", "review", "delivered", "maintenance", "cancelled"]>;
    totalAmount: zod.ZodNumber;
    paidAmount: zod.ZodNumber;
    dueDate: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    deliveredAt: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    notes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    status: "delivered" | "maintenance" | "pending" | "paid" | "in_progress" | "review" | "cancelled";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    clientId: number;
    title: string;
    packageType: "custom" | "basic_website" | "premium_website" | "seo" | "hosting" | "maintenance" | "ads_management" | "reputation_management";
    totalAmount: number;
    paidAmount: number;
    notes?: string | null | undefined;
    serviceId?: number | null | undefined;
    dueDate?: Date | null | undefined;
    deliveredAt?: Date | null | undefined;
}, {
    status: "delivered" | "maintenance" | "pending" | "paid" | "in_progress" | "review" | "cancelled";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    clientId: number;
    title: string;
    packageType: "custom" | "basic_website" | "premium_website" | "seo" | "hosting" | "maintenance" | "ads_management" | "reputation_management";
    totalAmount: number;
    paidAmount: number;
    notes?: string | null | undefined;
    serviceId?: number | null | undefined;
    dueDate?: Date | null | undefined;
    deliveredAt?: Date | null | undefined;
}>, "many">;
/**
 * @summary Create an order
 */
export declare const CreateOrderBody: zod.ZodObject<{
    clientId: zod.ZodNumber;
    serviceId: zod.ZodOptional<zod.ZodNumber>;
    title: zod.ZodString;
    packageType: zod.ZodEnum<["basic_website", "premium_website", "seo", "hosting", "maintenance", "ads_management", "reputation_management", "custom"]>;
    status: zod.ZodOptional<zod.ZodEnum<["pending", "paid", "in_progress", "review", "delivered", "maintenance", "cancelled"]>>;
    totalAmount: zod.ZodNumber;
    paidAmount: zod.ZodOptional<zod.ZodNumber>;
    dueDate: zod.ZodOptional<zod.ZodDate>;
    notes: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    clientId: number;
    title: string;
    packageType: "custom" | "basic_website" | "premium_website" | "seo" | "hosting" | "maintenance" | "ads_management" | "reputation_management";
    totalAmount: number;
    status?: "delivered" | "maintenance" | "pending" | "paid" | "in_progress" | "review" | "cancelled" | undefined;
    notes?: string | undefined;
    serviceId?: number | undefined;
    paidAmount?: number | undefined;
    dueDate?: Date | undefined;
}, {
    clientId: number;
    title: string;
    packageType: "custom" | "basic_website" | "premium_website" | "seo" | "hosting" | "maintenance" | "ads_management" | "reputation_management";
    totalAmount: number;
    status?: "delivered" | "maintenance" | "pending" | "paid" | "in_progress" | "review" | "cancelled" | undefined;
    notes?: string | undefined;
    serviceId?: number | undefined;
    paidAmount?: number | undefined;
    dueDate?: Date | undefined;
}>;
/**
 * @summary Get order by ID
 */
export declare const GetOrderParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetOrderResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    clientId: zod.ZodNumber;
    serviceId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    title: zod.ZodString;
    packageType: zod.ZodEnum<["basic_website", "premium_website", "seo", "hosting", "maintenance", "ads_management", "reputation_management", "custom"]>;
    status: zod.ZodEnum<["pending", "paid", "in_progress", "review", "delivered", "maintenance", "cancelled"]>;
    totalAmount: zod.ZodNumber;
    paidAmount: zod.ZodNumber;
    dueDate: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    deliveredAt: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    notes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    status: "delivered" | "maintenance" | "pending" | "paid" | "in_progress" | "review" | "cancelled";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    clientId: number;
    title: string;
    packageType: "custom" | "basic_website" | "premium_website" | "seo" | "hosting" | "maintenance" | "ads_management" | "reputation_management";
    totalAmount: number;
    paidAmount: number;
    notes?: string | null | undefined;
    serviceId?: number | null | undefined;
    dueDate?: Date | null | undefined;
    deliveredAt?: Date | null | undefined;
}, {
    status: "delivered" | "maintenance" | "pending" | "paid" | "in_progress" | "review" | "cancelled";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    clientId: number;
    title: string;
    packageType: "custom" | "basic_website" | "premium_website" | "seo" | "hosting" | "maintenance" | "ads_management" | "reputation_management";
    totalAmount: number;
    paidAmount: number;
    notes?: string | null | undefined;
    serviceId?: number | null | undefined;
    dueDate?: Date | null | undefined;
    deliveredAt?: Date | null | undefined;
}>;
/**
 * @summary Update order
 */
export declare const UpdateOrderParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateOrderBody: zod.ZodObject<{
    title: zod.ZodOptional<zod.ZodString>;
    packageType: zod.ZodOptional<zod.ZodEnum<["basic_website", "premium_website", "seo", "hosting", "maintenance", "ads_management", "reputation_management", "custom"]>>;
    status: zod.ZodOptional<zod.ZodEnum<["pending", "paid", "in_progress", "review", "delivered", "maintenance", "cancelled"]>>;
    totalAmount: zod.ZodOptional<zod.ZodNumber>;
    paidAmount: zod.ZodOptional<zod.ZodNumber>;
    dueDate: zod.ZodOptional<zod.ZodDate>;
    deliveredAt: zod.ZodOptional<zod.ZodDate>;
    notes: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    status?: "delivered" | "maintenance" | "pending" | "paid" | "in_progress" | "review" | "cancelled" | undefined;
    notes?: string | undefined;
    title?: string | undefined;
    packageType?: "custom" | "basic_website" | "premium_website" | "seo" | "hosting" | "maintenance" | "ads_management" | "reputation_management" | undefined;
    totalAmount?: number | undefined;
    paidAmount?: number | undefined;
    dueDate?: Date | undefined;
    deliveredAt?: Date | undefined;
}, {
    status?: "delivered" | "maintenance" | "pending" | "paid" | "in_progress" | "review" | "cancelled" | undefined;
    notes?: string | undefined;
    title?: string | undefined;
    packageType?: "custom" | "basic_website" | "premium_website" | "seo" | "hosting" | "maintenance" | "ads_management" | "reputation_management" | undefined;
    totalAmount?: number | undefined;
    paidAmount?: number | undefined;
    dueDate?: Date | undefined;
    deliveredAt?: Date | undefined;
}>;
export declare const UpdateOrderResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    clientId: zod.ZodNumber;
    serviceId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    title: zod.ZodString;
    packageType: zod.ZodEnum<["basic_website", "premium_website", "seo", "hosting", "maintenance", "ads_management", "reputation_management", "custom"]>;
    status: zod.ZodEnum<["pending", "paid", "in_progress", "review", "delivered", "maintenance", "cancelled"]>;
    totalAmount: zod.ZodNumber;
    paidAmount: zod.ZodNumber;
    dueDate: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    deliveredAt: zod.ZodOptional<zod.ZodNullable<zod.ZodDate>>;
    notes: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    status: "delivered" | "maintenance" | "pending" | "paid" | "in_progress" | "review" | "cancelled";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    clientId: number;
    title: string;
    packageType: "custom" | "basic_website" | "premium_website" | "seo" | "hosting" | "maintenance" | "ads_management" | "reputation_management";
    totalAmount: number;
    paidAmount: number;
    notes?: string | null | undefined;
    serviceId?: number | null | undefined;
    dueDate?: Date | null | undefined;
    deliveredAt?: Date | null | undefined;
}, {
    status: "delivered" | "maintenance" | "pending" | "paid" | "in_progress" | "review" | "cancelled";
    id: number;
    createdAt: Date;
    updatedAt: Date;
    clientId: number;
    title: string;
    packageType: "custom" | "basic_website" | "premium_website" | "seo" | "hosting" | "maintenance" | "ads_management" | "reputation_management";
    totalAmount: number;
    paidAmount: number;
    notes?: string | null | undefined;
    serviceId?: number | null | undefined;
    dueDate?: Date | null | undefined;
    deliveredAt?: Date | null | undefined;
}>;
/**
 * @summary Delete order
 */
export declare const DeleteOrderParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
/**
 * @summary List service packages
 */
export declare const ListServicesResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    price: zod.ZodNumber;
    category: zod.ZodString;
    features: zod.ZodOptional<zod.ZodArray<zod.ZodString, "many">>;
    active: zod.ZodBoolean;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    name: string;
    id: number;
    active: boolean;
    createdAt: Date;
    updatedAt: Date;
    category: string;
    price: number;
    description?: string | null | undefined;
    features?: string[] | undefined;
}, {
    name: string;
    id: number;
    active: boolean;
    createdAt: Date;
    updatedAt: Date;
    category: string;
    price: number;
    description?: string | null | undefined;
    features?: string[] | undefined;
}>;
export declare const ListServicesResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    price: zod.ZodNumber;
    category: zod.ZodString;
    features: zod.ZodOptional<zod.ZodArray<zod.ZodString, "many">>;
    active: zod.ZodBoolean;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    name: string;
    id: number;
    active: boolean;
    createdAt: Date;
    updatedAt: Date;
    category: string;
    price: number;
    description?: string | null | undefined;
    features?: string[] | undefined;
}, {
    name: string;
    id: number;
    active: boolean;
    createdAt: Date;
    updatedAt: Date;
    category: string;
    price: number;
    description?: string | null | undefined;
    features?: string[] | undefined;
}>, "many">;
/**
 * @summary Create a service package
 */
export declare const CreateServiceBody: zod.ZodObject<{
    name: zod.ZodString;
    description: zod.ZodOptional<zod.ZodString>;
    price: zod.ZodNumber;
    category: zod.ZodString;
    features: zod.ZodOptional<zod.ZodArray<zod.ZodString, "many">>;
    active: zod.ZodOptional<zod.ZodBoolean>;
}, "strip", zod.ZodTypeAny, {
    name: string;
    category: string;
    price: number;
    active?: boolean | undefined;
    description?: string | undefined;
    features?: string[] | undefined;
}, {
    name: string;
    category: string;
    price: number;
    active?: boolean | undefined;
    description?: string | undefined;
    features?: string[] | undefined;
}>;
/**
 * @summary Update service
 */
export declare const UpdateServiceParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateServiceBody: zod.ZodObject<{
    name: zod.ZodOptional<zod.ZodString>;
    description: zod.ZodOptional<zod.ZodString>;
    price: zod.ZodOptional<zod.ZodNumber>;
    category: zod.ZodOptional<zod.ZodString>;
    features: zod.ZodOptional<zod.ZodArray<zod.ZodString, "many">>;
    active: zod.ZodOptional<zod.ZodBoolean>;
}, "strip", zod.ZodTypeAny, {
    name?: string | undefined;
    active?: boolean | undefined;
    category?: string | undefined;
    description?: string | undefined;
    price?: number | undefined;
    features?: string[] | undefined;
}, {
    name?: string | undefined;
    active?: boolean | undefined;
    category?: string | undefined;
    description?: string | undefined;
    price?: number | undefined;
    features?: string[] | undefined;
}>;
export declare const UpdateServiceResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    price: zod.ZodNumber;
    category: zod.ZodString;
    features: zod.ZodOptional<zod.ZodArray<zod.ZodString, "many">>;
    active: zod.ZodBoolean;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    name: string;
    id: number;
    active: boolean;
    createdAt: Date;
    updatedAt: Date;
    category: string;
    price: number;
    description?: string | null | undefined;
    features?: string[] | undefined;
}, {
    name: string;
    id: number;
    active: boolean;
    createdAt: Date;
    updatedAt: Date;
    category: string;
    price: number;
    description?: string | null | undefined;
    features?: string[] | undefined;
}>;
/**
 * @summary Delete service
 */
export declare const DeleteServiceParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
/**
 * @summary List activities
 */
export declare const ListActivitiesQueryParams: zod.ZodObject<{
    leadId: zod.ZodOptional<zod.ZodNumber>;
    clientId: zod.ZodOptional<zod.ZodNumber>;
    type: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    type?: string | undefined;
    clientId?: number | undefined;
    leadId?: number | undefined;
}, {
    type?: string | undefined;
    clientId?: number | undefined;
    leadId?: number | undefined;
}>;
export declare const ListActivitiesResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    leadId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    clientId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    userId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    type: zod.ZodEnum<["call", "email", "whatsapp", "sms", "note", "meeting", "proposal", "ai_outreach"]>;
    subject: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    content: zod.ZodString;
    outcome: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    type: "email" | "call" | "whatsapp" | "sms" | "note" | "meeting" | "proposal" | "ai_outreach";
    id: number;
    createdAt: Date;
    content: string;
    clientId?: number | null | undefined;
    leadId?: number | null | undefined;
    userId?: number | null | undefined;
    subject?: string | null | undefined;
    outcome?: string | null | undefined;
}, {
    type: "email" | "call" | "whatsapp" | "sms" | "note" | "meeting" | "proposal" | "ai_outreach";
    id: number;
    createdAt: Date;
    content: string;
    clientId?: number | null | undefined;
    leadId?: number | null | undefined;
    userId?: number | null | undefined;
    subject?: string | null | undefined;
    outcome?: string | null | undefined;
}>;
export declare const ListActivitiesResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    leadId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    clientId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    userId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    type: zod.ZodEnum<["call", "email", "whatsapp", "sms", "note", "meeting", "proposal", "ai_outreach"]>;
    subject: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    content: zod.ZodString;
    outcome: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    type: "email" | "call" | "whatsapp" | "sms" | "note" | "meeting" | "proposal" | "ai_outreach";
    id: number;
    createdAt: Date;
    content: string;
    clientId?: number | null | undefined;
    leadId?: number | null | undefined;
    userId?: number | null | undefined;
    subject?: string | null | undefined;
    outcome?: string | null | undefined;
}, {
    type: "email" | "call" | "whatsapp" | "sms" | "note" | "meeting" | "proposal" | "ai_outreach";
    id: number;
    createdAt: Date;
    content: string;
    clientId?: number | null | undefined;
    leadId?: number | null | undefined;
    userId?: number | null | undefined;
    subject?: string | null | undefined;
    outcome?: string | null | undefined;
}>, "many">;
/**
 * @summary Log an activity
 */
export declare const CreateActivityBody: zod.ZodObject<{
    leadId: zod.ZodOptional<zod.ZodNumber>;
    clientId: zod.ZodOptional<zod.ZodNumber>;
    type: zod.ZodEnum<["call", "email", "whatsapp", "sms", "note", "meeting", "proposal", "ai_outreach"]>;
    subject: zod.ZodOptional<zod.ZodString>;
    content: zod.ZodString;
    outcome: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    type: "email" | "call" | "whatsapp" | "sms" | "note" | "meeting" | "proposal" | "ai_outreach";
    content: string;
    clientId?: number | undefined;
    leadId?: number | undefined;
    subject?: string | undefined;
    outcome?: string | undefined;
}, {
    type: "email" | "call" | "whatsapp" | "sms" | "note" | "meeting" | "proposal" | "ai_outreach";
    content: string;
    clientId?: number | undefined;
    leadId?: number | undefined;
    subject?: string | undefined;
    outcome?: string | undefined;
}>;
/**
 * @summary Delete activity
 */
export declare const DeleteActivityParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
/**
 * @summary Get overall dashboard statistics
 */
export declare const GetDashboardStatsResponse: zod.ZodObject<{
    totalLeads: zod.ZodNumber;
    totalClients: zod.ZodNumber;
    totalRevenue: zod.ZodNumber;
    monthlyRevenue: zod.ZodNumber;
    activeOrders: zod.ZodNumber;
    conversionRate: zod.ZodNumber;
    newLeadsThisWeek: zod.ZodNumber;
    closedDealsThisMonth: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    totalRevenue: number;
    totalLeads: number;
    totalClients: number;
    monthlyRevenue: number;
    activeOrders: number;
    conversionRate: number;
    newLeadsThisWeek: number;
    closedDealsThisMonth: number;
}, {
    totalRevenue: number;
    totalLeads: number;
    totalClients: number;
    monthlyRevenue: number;
    activeOrders: number;
    conversionRate: number;
    newLeadsThisWeek: number;
    closedDealsThisMonth: number;
}>;
/**
 * @summary Get lead pipeline breakdown
 */
export declare const GetPipelineStatsResponseItem: zod.ZodObject<{
    stage: zod.ZodString;
    count: zod.ZodNumber;
    value: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    value: number;
    stage: string;
    count: number;
}, {
    value: number;
    stage: string;
    count: number;
}>;
export declare const GetPipelineStatsResponse: zod.ZodArray<zod.ZodObject<{
    stage: zod.ZodString;
    count: zod.ZodNumber;
    value: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    value: number;
    stage: string;
    count: number;
}, {
    value: number;
    stage: string;
    count: number;
}>, "many">;
/**
 * @summary Get monthly revenue data
 */
export declare const GetRevenueDataResponseItem: zod.ZodObject<{
    month: zod.ZodString;
    revenue: zod.ZodNumber;
    orders: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    month: string;
    revenue: number;
    orders: number;
}, {
    month: string;
    revenue: number;
    orders: number;
}>;
export declare const GetRevenueDataResponse: zod.ZodArray<zod.ZodObject<{
    month: zod.ZodString;
    revenue: zod.ZodNumber;
    orders: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    month: string;
    revenue: number;
    orders: number;
}, {
    month: string;
    revenue: number;
    orders: number;
}>, "many">;
/**
 * @summary Get recent activity feed
 */
export declare const GetRecentActivityResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    leadId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    clientId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    userId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    type: zod.ZodEnum<["call", "email", "whatsapp", "sms", "note", "meeting", "proposal", "ai_outreach"]>;
    subject: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    content: zod.ZodString;
    outcome: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    type: "email" | "call" | "whatsapp" | "sms" | "note" | "meeting" | "proposal" | "ai_outreach";
    id: number;
    createdAt: Date;
    content: string;
    clientId?: number | null | undefined;
    leadId?: number | null | undefined;
    userId?: number | null | undefined;
    subject?: string | null | undefined;
    outcome?: string | null | undefined;
}, {
    type: "email" | "call" | "whatsapp" | "sms" | "note" | "meeting" | "proposal" | "ai_outreach";
    id: number;
    createdAt: Date;
    content: string;
    clientId?: number | null | undefined;
    leadId?: number | null | undefined;
    userId?: number | null | undefined;
    subject?: string | null | undefined;
    outcome?: string | null | undefined;
}>;
export declare const GetRecentActivityResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    leadId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    clientId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    userId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    type: zod.ZodEnum<["call", "email", "whatsapp", "sms", "note", "meeting", "proposal", "ai_outreach"]>;
    subject: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    content: zod.ZodString;
    outcome: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    type: "email" | "call" | "whatsapp" | "sms" | "note" | "meeting" | "proposal" | "ai_outreach";
    id: number;
    createdAt: Date;
    content: string;
    clientId?: number | null | undefined;
    leadId?: number | null | undefined;
    userId?: number | null | undefined;
    subject?: string | null | undefined;
    outcome?: string | null | undefined;
}, {
    type: "email" | "call" | "whatsapp" | "sms" | "note" | "meeting" | "proposal" | "ai_outreach";
    id: number;
    createdAt: Date;
    content: string;
    clientId?: number | null | undefined;
    leadId?: number | null | undefined;
    userId?: number | null | undefined;
    subject?: string | null | undefined;
    outcome?: string | null | undefined;
}>, "many">;
/**
 * @summary Generate personalized AI outreach message
 */
export declare const GenerateOutreachBody: zod.ZodObject<{
    leadId: zod.ZodNumber;
    channel: zod.ZodEnum<["email", "whatsapp", "sms", "instagram"]>;
    tone: zod.ZodOptional<zod.ZodEnum<["professional", "friendly", "casual"]>>;
    serviceType: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    leadId: number;
    channel: "email" | "whatsapp" | "sms" | "instagram";
    tone?: "professional" | "friendly" | "casual" | undefined;
    serviceType?: string | undefined;
}, {
    leadId: number;
    channel: "email" | "whatsapp" | "sms" | "instagram";
    tone?: "professional" | "friendly" | "casual" | undefined;
    serviceType?: string | undefined;
}>;
export declare const GenerateOutreachResponse: zod.ZodObject<{
    subject: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    message: zod.ZodString;
    channel: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    message: string;
    channel: string;
    subject?: string | null | undefined;
}, {
    message: string;
    channel: string;
    subject?: string | null | undefined;
}>;
/**
 * @summary Generate AI sales proposal
 */
export declare const GenerateProposalBody: zod.ZodObject<{
    clientId: zod.ZodNumber;
    serviceIds: zod.ZodArray<zod.ZodNumber, "many">;
    customNotes: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    clientId: number;
    serviceIds: number[];
    customNotes?: string | undefined;
}, {
    clientId: number;
    serviceIds: number[];
    customNotes?: string | undefined;
}>;
export declare const GenerateProposalResponse: zod.ZodObject<{
    proposal: zod.ZodString;
    estimatedValue: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    proposal: string;
    estimatedValue: number;
}, {
    proposal: string;
    estimatedValue: number;
}>;
/**
 * @summary AI lead scoring
 */
export declare const ScoreLeadBody: zod.ZodObject<{
    leadId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    leadId: number;
}, {
    leadId: number;
}>;
export declare const ScoreLeadResponse: zod.ZodObject<{
    score: zod.ZodNumber;
    reasoning: zod.ZodString;
    recommendedAction: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    score: number;
    reasoning: string;
    recommendedAction: string;
}, {
    score: number;
    reasoning: string;
    recommendedAction: string;
}>;
//# sourceMappingURL=api.d.ts.map